# Netlify configuration for Coopec Kwilu PWA
[build]
  publish = "."

# Force SPA-style serving of indexo.html at all routes (no function changes)
[[redirects]]
  from = "/*"
  to = "/indexo.html"
  status = 200

# Service worker allowed to control the whole scope
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# PWA essentials: cache manifest + icons sensibly
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
